version: "3.8"

services:
  # Deploy-Code Service
  deploy-code:
    container_name: backend
    build:
      context: ./deploy-code
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./deploy-code:/app
      - /app/node_modules
    networks:
      - app_network

  # Frontend Service
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app_network

  # Event Service
  webhook-event-handler:
    container_name: webhook
    build:
      context: ./webhook-event-handler
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    volumes:
      - ./webhook-event-handler:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - FRONTEND_URL=http://frontend:5173
    networks:
      - app_network

  # Request-Handler Service
  request-handler:
    container_name: request-handler
    build:
      context: ./request-handler-v2
      dockerfile: Dockerfile
    ports:
      - "3003:3001"
    volumes:
      - ./request-handler-v2:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app_network

# Docker Networks
networks:
  app_network:
    driver: bridge

# Docker Volumes
volumes:
  redis_data:
    driver: local
