# Build stage
FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./
COPY tsconfig.json ./

# Install all dependencies (including devDependencies)
RUN npm install

# Copy source code
COPY . .

RUN tsc

EXPOSE 3001

CMD ["node","dist/index.js"]
