# Build stage
FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./
COPY tsconfig.json ./

# Install all dependencies (including devDependencies)
RUN npm install

# Install typescript globally
RUN npm install -g typescript

# Copy source code
COPY . .

RUN tsc

EXPOSE 3001

CMD ["node","dist/index.js"]
