# Start with the official Node.js image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json, package-lock.json, and tsconfig.json
COPY package*.json ./
COPY tsconfig.json ./

# Install dependencies
RUN npm install

# Copy the entire project into the container
COPY . .

# Ensure that the prisma folder and schema.prisma file are copied correctly
COPY prisma ./prisma

# Generate Prisma client after the code is copied
RUN npx prisma generate --schema=./prisma/schema.prisma

# Expose the port for your app
EXPOSE 3000

# Build the TypeScript project
RUN npm run build

# Start the application
CMD ["npm", "run", "dev"]
