name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Commit SHA
        run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # Docker Hub Login
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Login to AWS ECR
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-north-1

      - name: Login to AWS ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      # Make sure repositories exist
      - name: Create ECR repositories if they don't exist
        run: |
          for service in deploify-deploy-code deploify-frontend deploify-webhook-event-handler deploify-request-handler; do
            aws ecr describe-repositories --repository-names deploify/${service} || aws ecr create-repository --repository-name ${service}
          done
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Services
        run: |
            echo "Building all services with docker compose..."
            docker compose build
      - name: list images
        run: |
          docker images 

      # Tag & Push to Docker Hub
      - name: Push to Docker Hub
        run: |
          for service in deploify-deploy-code deploify-frontend deploify-webhook-event-handler deploify-request-handler; do
            echo "Pushing ${service} to Docker Hub..."
            docker tag ${service}:latest dhruvwebdev146/${service}:${COMMIT_SHA}
            docker tag ${service}:latest dhruvwebdev146/${service}:latest
            docker push dhruvwebdev146/${service}:${COMMIT_SHA}
            docker push dhruvwebdev146/${service}:latest
          done

      # Tag & Push to AWS ECR
      - name: Push to AWS ECR 
        run: |
          ECR_REGISTRY="${{ secrets.AWS_ECR_REGISTRY }}"
          if [ -z "$ECR_REGISTRY" ]; then
            ECR_REGISTRY="${{ steps.ecr-login.outputs.registry }}"
          fi
          
          for service in deploify-deploy-code deploify-frontend deploify-webhook-event-handler deploify-request-handler; do
            echo "Pushing ${service} to ECR at ${ECR_REGISTRY}..."
            docker tag ${service}:latest ${ECR_REGISTRY}/deploify/${service}:${COMMIT_SHA}
            docker tag ${service}:latest ${ECR_REGISTRY}/deploify/${service}:latest
            docker push ${ECR_REGISTRY}/${service}:${COMMIT_SHA}
            docker push ${ECR_REGISTRY}/${service}:latest
          done