name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Commit SHA
        run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # Docker Hub Login
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      # AWS ECR Login
      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REGISTRY }}

      # Build Docker Images
      - name: Build Services
        run: docker compose build

      # Tag & Push to Docker Hub
      - name: Push to Docker Hub
        run: |
          for service in deploy-code frontend event request-handler; do
            docker tag $service dhruvwebdev146/$service:${{ env.COMMIT_SHA }}
            docker tag $service dhruvwebdev146/$service:latest
            docker push dhruvwebdev146/$service:${{ env.COMMIT_SHA }}
            docker push dhruvwebdev146/$service:latest
          done

      # Tag & Push to AWS ECR
      - name: Push to AWS ECR
        run: |
          for service in deploy-code frontend event request-handler; do
            docker tag $service ${{ secrets.AWS_ECR_REGISTRY }}/$service:${{ env.COMMIT_SHA }}
            docker tag $service ${{ secrets.AWS_ECR_REGISTRY }}/$service:latest
            docker push ${{ secrets.AWS_ECR_REGISTRY }}/$service:${{ env.COMMIT_SHA }}
            docker push ${{ secrets.AWS_ECR_REGISTRY }}/$service:latest
          done
